### ISSUE TITLE
Add Animations to Buttons and Sections for a Smoother User Experience

### ISSUE THREAD

**Issue by OleksandrZadvornyi** [OleksandrZadvornyi/E-learnWebsite#2]
## Summary
Introduce subtle animations to buttons and sections to enhance user experience by providing visual feedback and smoother transitions.

### Basic example
Add CSS animations to buttons for hover and click events, as well as fade-in or slide-in effects for sections when they appear on the screen. For example:

```css
/* Button hover animation */
.button {
  transition: transform 0.2s ease, background-color 0.3s ease;
}

.button:hover {
  transform: scale(1.05);
  background-color: #0056b3;
}

/* Section fade-in animation */
@keyframes fadeIn {
  from {
    opacity: 0;
    transform: translateY(20px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.section {
  animation: fadeIn 0.5s ease-in;
}
```

### Motivation
Adding animations will make interactions more engaging and visually appealing, improving the overall user experience. Smooth transitions can help guide the user’s attention to important elements and create a more polished and professional feel for the website.
